[2024-12-13 18:26:43,298][zerorpc.core][ERROR] - 
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "reactive_tamp.py", line 125, in run_tamp
    self.motion_planner.command(self.sim._dof_state[0])[0]
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/mppi.py", line 245, in command
    cost_total = self._compute_total_cost_batch_halton()
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/mppi.py", line 419, in _compute_total_cost_batch_halton
    self.cost_total, self.states, self.actions, self.ee_states = self._compute_rollout_costs(self.perturbed_action)
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/mppi.py", line 306, in _compute_rollout_costs
    c = self._running_cost(state) # every time stes you get nsamples cost, we need that as output for the discount factor
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/mppi.py", line 210, in _running_cost
    return self.running_cost(state)
  File "reactive_tamp.py", line 138, in running_cost
    return self.objective.compute_cost(self.sim)
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/cost_functions1.py", line 84, in compute_cost
    get_motion_cost_1 = self.get_motion_cost_1(sim)
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/cost_functions1.py", line 264, in get_motion_cost_1
    distance, self.nn_grad = self.distance_repulsion_nn(sim, q_prev, aot=False)
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/motion_planner/cost_functions1.py", line 435, in distance_repulsion_nn
    nn_dist, nn_grad, nn_minidx = self.nn_model.dist_grad_closest(nn_input[:, 0:-1])
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/mlp_learn/sdf/robot_sdf.py", line 127, in dist_grad_closest
    dist_scale = self.model.forward(q)
  File "/home/my/m3p2i-aip-master/src/m3p2i_aip/planners/mlp_learn/sdf/network_macros_mod.py", line 143, in forward
    y = self.layers[0](x_nerf)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (82x27 and 30x256)
